### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 9xN** [roccomuso/netcat#19]
```
net.js:1345
  self.emit('error', err);
       ^

TypeError: Cannot read property 'emit' of undefined
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
sh-3.2$ 
```

**Comment by roccomuso** [comment]
What are you trying to achieve?
can you paste full code?

**Comment by 9xN** [comment]
so long ago i forget what thats from if i ever find it again ill let you know
