### ISSUE TITLE
Windows build test failed.

### ISSUE THREAD

**Issue by roccomuso** [roccomuso/netcat#2]
- [x] `type` on win has a different behaviour compared to unix `cat`.

```
  Server exec()
    √ spawning process
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn type ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by roccomuso** [comment]
Fallback on an external `cat.exe`.
